### PR TITLE
added svg content-type

### PR DESCRIPTION
**Pull request by yagelix**
I've added explicitly image/svg+xml as SVG content type. It allows to avoid crashes when the presentaiton already contains svg images and new picture is to be added to a slide (see #382)

### CODE REVIEW

**Comment by scanny** [comment]
Thanks for this @yagelix, will see about getting this into the build on the next release coming up in a few weeks :)

**Comment by yagelix** [comment]
I've just added a fix for similar problem with mp3 files embedded .

**Comment by scanny** [comment]
One question on this @yagelix, on the SVG part. So adding that content type allows the presentation containing SVGs to be loaded; I assume these were created with PowerPoint 2016, is that right?

Have you tested adding an SVG graphic using `shapes.add_picture()`? I'm thinking that either doesn't work (which is the best outcome) or causes a repair error (which I what I expect happens).

If you can attach in a simple file that contains a single slide with only an SVG image on it, I'd like to inspect how they do it. What I'm imagining is that they provide a WMF (Windows Metafile) format alternative, which would likely rule out our supporting actually adding that type of image (until Pillow supports that transformation).

**Comment by yagelix** [comment]
1. shapes.add_picture()  for svg doesn't work, because PIL is used to read for each image blob (it's not needed in my case -- I'm only adding PNG images). May be the image should be checked to be supported by PIL (raster) first in try block, then, in catch block -- left as is without pil data filling.
2.  [Here](https://github.com/yagelix/python-pptx/blob/svg_support/tests/test_files/test_svg_icons.pptx) is the test file with SVGs -- looks like there is no any WMF there.

**Comment by scanny** [comment]
Ah, interesting. So that's actually good news. The thing we want to avoid is enabling a developer to create a `.pptx` file with a repair error, without having a clear idea why that happened. So it sounds like adding this content type fixes loading errors that may crop up now with the new SVG support, and doesn't sound like it has any nasty side effects. That's good news :)

Btw, how were these pptx files with SVGs in them created, i.e. what version of PowerPoint was used?

**Comment by yagelix** [comment]
At least PowerPoint2018 allows to use SVG images.

**Comment by jdelight** [comment]
This would be a great addition - thanks @yagelix / @scanny 👍

**Comment by morocarlo** [comment]
can you merge it and realease? This fix is working for me :)

**Comment by jdelight** [comment]
Does this allow you to insert .svg files into PicturePlaceholder? Would be great to have an example... maybe that's what is holding up the merge @morocarlo ? I would imaging with the recent update to Powerpoint - a lot of people will be migrating to use SVGs wherever possible.

**Comment by scanny** [comment]
Fixed in release v0.6.12 circa August 11, 2018.

@yagelix I took a different approach that I believe will be more robust. I added a guard in `_ImageParts._find_by_sha1()` that skips over parts that don't have a `.sha1` attribute (such as the default `Part`). This avoids the load error without opening the door to other side-effect bugs that might arise from SVG image parts being different in important ways from other image parts.

**Pull request closed without merging**
