### PR TITLE
Add a line property to _BaseAxis

### PR DESCRIPTION
**Pull request by kevingu1003**
Add a line property to _BaseAxis so the line for axes in charts can be formatted (color, width etc.).

### CODE REVIEW

**Comment by scanny** [comment]
Looks pretty good, but will need tests before I could commit.

**Comment by buzzm** [comment]
Hello!  Apols if this is the wrong channel for comms; it's my first time actually engaging a github repo owner that I don't know directly.

I raised an issue on python-pptx in June (#170) re. removing the seek(0) because it broke some file-like objects that do not support seek() -- especially web-based ones that are very useful for retrieving remote images and other material.

Should I start a pull process on this?   I've never done a pull before because, again, I usually know the owner and they incorporate the change themselves.

The library is great and I look forward to when speaker notes read/write is incorporated.   That will close the loop on completely automating many presentations requiring backing material for the points on the slides.

**Comment by scanny** [comment]
Hi @buzzm, this channel works fine. A pull request is good, but the challenge of a commit starts a long way before the actual code changes. Those turn out to be the easiest part in my experience, something that seems to escape most pull submitters.

One of the challenges we have is that right now there are no active developers on the project. So unfortunately no way to quickly slip it into anyone's well-worn workflow at the moment.

In general the project style is outside->in, so the place to start is with the end-user experience. And this work is useful even if it doesn't include the code changes. Like I said, that part is generally the easiest.

In support of the review, you would want to identify the analysis that's already been done. That will be somewhere under here: http://python-pptx.readthedocs.org/en/latest/dev/analysis/index.html. It looks like under Shapes and Picture Placeholder from a quick look, I can't remember why we don't have anything more detailed. Anyway, this is mostly just context/background, however you should also consider what changes if any are called for in the end-user documentation.

Next would be to identify the acceptance tests that exercise this and propose how they would need to change, if at all. Those are located here: https://github.com/scanny/python-pptx/tree/master/features. I suppose it would include sld-add-picture.feature, but worth a quick check through to make sure nothing else is involved. I would check placeholders for example, I believe there's a picture placeholder in there. It could be a good idea to have a new separate scenario for loading from a non-seekable stream, whatever they're more properly called.

This is where the change in the end-user experience would show up. You want to make it so the reviewer (me likely) doesn't have to go through and do that analysis themselves to have confidence you're not introducing a bug.

Next is the unit tests. I think that will be limited to here: https://github.com/scanny/python-pptx/blob/master/tests/shapes/test_shapetree.py#L236, but again worth a look around or a grep/ag on .add_picture to make sure that's the only place it's exercised. There will definitely need to be at least a small change here, because the tests currently pass. So there needs to be a new test (probably not just a tweak to an existing one), perhaps something like `it_can_add_a_picture_from_a_url()`. Once this is in and failing, then we're close.

Finally, the code change to remove the seek(0) and make sure all the other tests still pass.

The commits would be:

* One for the analysis changes, if any, and any other documentation except API (class/method) docstrings
* One for any acceptance test changes, marked @wip because they'll need to be failing.
* One for each unit test change and the code changes that make it pass.

Let me know if you need more, happy to work on this with you :)

**Comment by buzzm** [comment]
VERY comprehensive reply; thanks for the detail!
Let me digest this and let's see what's good for a next step.   Very different from my days with perl and CPAN.   :-)
At the moment I have a locally hacked version with seek(0) removed and all is working well so there's no urgency here.

**Comment by Majeed-Sahebzadha** [comment]
1+ useful to have!

**Comment by scanny** [comment]
Added _BaseAxis.format with v0.6.0 release uploaded to PyPI today. This property provides access to .line and .fill, which implements this functionality.

**Pull request closed without merging**
