### PR TITLE
Add BAR_STACKED and COLUMN_STACKED chart type implementations.

### PR DESCRIPTION
**Pull request by rokclimb15**

### CODE REVIEW

**Comment by leng** [comment]
Hi, any chance this will get merged to master in the near future? Thanks!

**Comment by rokclimb15** [comment]
Does this need any improvements in order to merge?

**Comment by scanny** [comment]
Needs acceptance and unit tests. Models should already be there for the other chart types, might just be able to add a scenario or two.

https://github.com/scanny/python-pptx/blob/master/features/cht-chart-props.feature
https://github.com/scanny/python-pptx/blob/master/features/steps/chart.py
https://github.com/scanny/python-pptx/blob/master/tests/chart/test_chart.py#L80

**Comment by jaleskovec** [comment]
I've pulled these changes into pull request https://github.com/scanny/python-pptx/pull/184 and finished the tests.

**Comment by scanny** [comment]
These were both added a while back.

**Pull request closed without merging**
