### PR TITLE
Fix == instead of = in MSO_LINE_DASH_STYLE docs

### PR DESCRIPTION
**Pull request by ewelkaw**

### CODE REVIEW

**Comment by scanny** [comment]
Good catch @ewelkaw, I'll get this in the next release :)

**Comment by ewelkaw** [comment]
Thank you ;)
W dniu pon., 28.12.2020 o 22:42 Steve Canny <notifications@github.com>
napisał(a):

**Comment by scanny** [comment]
Fixed in v0.6.19 on May 16, 2021.

**Comment by ewelkaw** [comment]
Thanks ;)

W dniu niedz., 16.05.2021 o 23:44 Steve Canny ***@***.***>
napisał(a):

**Pull request closed without merging**
