### PR TITLE
Stacked Bar, Column and Area Charts

### PR DESCRIPTION
**Pull request by jaleskovec**
I've pulled the changes from pull request 125 (https://github.com/scanny/python-pptx/pull/125) and completed the tests. I've also added column stacked 100, area, area stacked and area stacked 100.

### CODE REVIEW

**Comment by rokclimb15** [comment]
Thanks @jaleskovec !

**Comment by jaleskovec** [comment]
I believe the failing tests are unrelated to my changes. Can you please check?

Also, attached is a sample pptx file with the stacked charts.
[pptx_stacked_demo.pptx](https://github.com/scanny/python-pptx/files/45924/pptx_stacked_demo.pptx)


.

**Comment by scanny** [comment]
@jaleskovec Yes, I think you're right. It might have something to do with travis upgrading its infrastructure. I'll see if I can clear it.

**Comment by scanny** [comment]
Ok, mine works fine, so I'm thinking its because this is based on the 0.5.1 release.

Want to rebase onto the latest and see if that fixes it?

I'm working on the code this week, so can probably get it committed while I'm in there.

**Comment by jaleskovec** [comment]
Worked like a charm. Thanks for checking.

**Comment by glawas** [comment]
Any chance this will get merged anytime soon?

**Comment by scanny** [comment]
Hi @jaleskovec -- apologies it's taken me so long to get to this, just freed up from some other projects so have some time again to attend to it.

What I'll need for a start is to have the pull request in its own branch, say "feature/stacked-charts", based/rooted on the latest develop branch from scanny/python-pptx. That will probably take some rebasing on your side, but is the only way to get this merged cleanly without disrupting the commit history. I don't have enough experience with pull requests to know, but I think this will entail a new pull request because it will be a different branch. After that we should be able to add changes as required without creating new pull requests just by you rebasing in the same branch and the pushing that branch with the -f(orce) option.

Second, we should have an analysis page (that can be the first commit), that lays out the scope of what you're doing and outlines the changes and such. There are examples here:
http://python-pptx.readthedocs.org/en/latest/dev/analysis/features/cht-bar-chart.html

You can probably cut and paste most of the XML Schema bits from existing pages. They're located in docs/dev/analysis/features. There are a small collection of pages devoted to charts, so I expect this will be readily assembled mostly from bits and pieces there.

All we need is enough to understand how the stacked charts work, XML snippets that show the cases etc. I recommend making a quick draft with whatever you have off the top of your head and then I can ask for anything else I need. Once I understand how it works we'll be done with that bit.

The acceptance tests look pretty good. We'll need some added to features/cht-chart-props.feature to test that the .chart_type property correctly identifies known stacked charts, but we can get to that in due course.

There's likely to be a fair amount of rebasing to get the commits in order and parceled appropriately, so I'm hoping you're facile with `git rebase` :)  In particular, the analysis comes first, then the acceptance tests (marked @wip) in the next commit, then one commit for each atomic functionality bit added. Generally these are a single new unit test with the code that makes that test pass. The thing that determines what bit gets added next is what needs to get implemented to get the acceptance test error to change to the next step. If you review the commit history you'll see that repeating pattern.

Anyway, let me know how you go and we can get this moving again. Apologies again for the delay, it looks like you've got the lion's share of this worked out and very nicely too. Looking forward to getting it merged in and working with you :)

**Comment by scanny** [comment]
@glawas - thanks for the reminder Gilberto, I'd been meaning to get back to this now that I've freed up a little :)

**Comment by jaleskovec** [comment]
Added https://github.com/scanny/python-pptx/pull/197 with features docs and a fixed commit sequence. It was easier to just reapply the changes than to rebase the commits. Let me know if any other changes are required.

**Pull request closed without merging**
